Models/Projects/License.cs
using System.ComponentModel.DataAnnotations;

namespace Project_Management.Models.Projects
{
    public class License
    {
       public int Id { get; set; }
        [Display(Name = "License Name")]
        public string Name { get; set; }
        [Display(Name = "Project Id")]
        public string Project_id { get; set; }
        [Display(Name = "Expiry Date")]
        public DateTime Expiry_Date { get; set; }
        
        public License()
        {}
        public License(License model, string projetId)
        {
            Project_id = projetId;
            Name = model.Name;
            Expiry_Date = model.Expiry_Date;
        }
    }
}

Models/Projects/Project.cs
using System.ComponentModel.DataAnnotations;

namespace Project_Management.Models.Projects
{
    public class Project
    {
        public int Id { get; set; }
        [Display(Name = "Project Id")]
        public string Project_Id { get; set; }
        [Display(Name = "Project Name")]
        public string Project_name { get; set; }
        [Display(Name  = "Start Date")]
        public DateTime Start_Date { get; set; }
        public string Description { get; set; }
        public int User_Id { get; set; }

        public Project()
        {

        }
        public Project(Project model, int userid)
        {
            Random rand = new Random();
            int randomNumber = rand.Next(100, 1000);

            Project_Id = "pro" + randomNumber.ToString();
            Project_name = model.Project_name;
            Description = model.Description;
            Start_Date = model.Start_Date;
            User_Id = userid;
        }
    }
    
   
}

Controllers/LicenseController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Management.Data;
using Microsoft.EntityFrameworkCore;
using Project_Management.Models.Projects;
using System.Diagnostics.Metrics;
using System.Security.Claims;
using Project_Management.Models.Account;
using Microsoft.AspNetCore.Authorization;

namespace Project_Management.Controllers
{
    [Authorize]
    public class LicenseController : Controller
    {
        private readonly ProjectContext _context;
        public LicenseController (ProjectContext context)
        {
            _context = context;
        }
        //Return view for Add License
        [HttpGet]
        public IActionResult AddLicense(int id)
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            if (User.Identity.IsAuthenticated)
           {
                var project = _context.Project.Where(p => p.Id == id).FirstOrDefault();
                var license = _context.License.Where(l => l.Project_id == project.Project_Id).FirstOrDefault();
                if (license != null)
                {

                    return RedirectToAction("UpdateLicense", new { id = license.Id });
                }
                return View();
           }
            return NotFound();
        }
        //Add license to database
        [HttpPost]
        [Route("License/AddLicense")]
        [ValidateAntiForgeryToken]
        public IActionResult AddLicense(License model)
        {
            try
            {
                string projectIdString = model.Project_id;
                int projectId;
                int.TryParse(projectIdString, out projectId);
                var project = _context.Project.Where( p => p.Id == projectId).FirstOrDefault();
                //get the logged in user id and convert it into integer
                if (User.Identity.IsAuthenticated)
                {
                    // add new record of project
                    var data = new License(model, project.Project_Id);
                    _context.Add(data);
                    _context.SaveChanges();
                    return RedirectToAction("GetPorject","Project");
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while adding project record.";
                return View(TempData);
            }
        }
        //Delete license from database
        [HttpPost]
        public IActionResult DeleteLicense(int id)
        {
            try
            {
                var record = _context.License.Where(r => r.Id == id).FirstOrDefault();
                if (record != null)
                {
                    _context.Remove(record);
                    _context.SaveChanges();
                    return RedirectToAction("GetPorject","Project");
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while deleting license record.";
                return View(TempData);
            }
        }
        //Return view for Update license 
        [HttpGet]
        public IActionResult UpdateLicense(int id) 
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var license = _context.License.Where(l => l.Id == id).FirstOrDefault();
                    if (license != null)
                    {
                    return View(license);
                    }
                return NotFound();
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while retrieving license record.";
                return View(TempData);
            }
        }
        //Update license in database
        [HttpPost]
        public IActionResult UpdateLicense(License model)
        {
            try
            {
                var license = _context.License.Where(l => l.Id == model.Id).FirstOrDefault();
                license.Name = model.Name;
                license.Expiry_Date = model.Expiry_Date;
                _context.SaveChanges();
                return RedirectToAction("GetPorject","Project");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while updating license record.";
                return View(TempData);
            }
        }
        //Get the all license records from database
        [HttpGet]
        public async Task<IActionResult> GetLicense()
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var license = await _context.License.ToListAsync();
                    return View(license);
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while retrieving projects.";
                return View(TempData);
            }
        }
    }
}

Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project_Management.Data;
using Project_Management.Models.Account;
using Project_Management.Models.Projects;
using Project_Management.Models.ViewModels;
using System.Diagnostics.Metrics;
using System.Security.Claims;

namespace Project_Management.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly ProjectContext _context;

        public ProjectController(ProjectContext context)
        {
            _context = context;
        }
        //Return view for Add License
        [HttpGet]
        public IActionResult AddPorject()
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            if (User.Identity.IsAuthenticated)
            {
                return View("AddProject");
            }
            return NotFound();
        }
        //Add license to database
        [HttpPost]
        public IActionResult AddPorject(Project model)
        {
            try
            {
                //get the logged in user id and convert it into integer
                string userId = null;
                if (User.Identity.IsAuthenticated)
                {

                    userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                }
                int userId1;
                int.TryParse(userId, out userId1);
                // add new record of project
                var data = new Project(model, userId1);
                _context.Add(data);
                _context.SaveChanges();
                return RedirectToAction("GetPorject");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while adding project record.";
                return View(TempData);
            }
        }
        //Delete license from database
        [HttpPost]
        public IActionResult DeletePorject(int id)
        {
            try
            {
                var record = _context.Project.Where( r => r.Id == id ).FirstOrDefault();
                if (record != null)
                {
                    _context.Remove(record);
                    var license = _context.License.Where(l => l.Project_id == record.Project_Id).FirstOrDefault();
                    if (license != null)
                    {
                        _context.Remove(license);
                    }
                    _context.SaveChanges();
                    return RedirectToAction("GetPorject");
                }
                return NotFound();
            }
           catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while deleting project record.";
                return View(TempData);
            }
        }
        //Return view for Update license 
        [HttpGet]
        public IActionResult UpdatePorject(int id)
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var project = _context.Project.Where(p => p.Id == id).FirstOrDefault();
                    if (project != null)
                    {
                        return View(project);
                    }
                    return NotFound();
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while retrieving project record.";
                return View(TempData);
            }
        }
        //Update license in database
        [HttpPost]
        public IActionResult UpdatePorject(Project model)
        {
            try
            {
            var project = _context.Project.Where(p => p.Id == model.Id).FirstOrDefault();
                project.Project_name = model.Project_name;
                project.Description = model.Description;
                project.Start_Date = model.Start_Date;
                _context.SaveChanges();
                return RedirectToAction("GetPorject");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while updating project record.";
                return View(TempData);
            }
            
        }
        //Get the all license records from database
        [HttpGet]
        public async Task<IActionResult> GetPorject()
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            try
            {
                string userId = null;
                if (User.Identity.IsAuthenticated)
                {

                    userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    int userId1;
                    int.TryParse(userId, out userId1);
                    var projects = await _context.Project.Where(tm => tm.User_Id == userId1).ToListAsync();

                    return View(projects);
                }
               return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while retrieving projects.";
                return View(TempData);
            }
        }

        [HttpGet]
        public IActionResult ProjectDetails(int id)
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            try
            {
                if(User.Identity.IsAuthenticated)
                {
                    var projects = _context.Project.Where(p => p.Id == id).FirstOrDefault();
                    var licenses = _context.License.Where(l => l.Project_id == projects.Project_Id).FirstOrDefault();
                    if (licenses != null)
                    {
                        var details = new ProjectLicense
                        {
                            project = projects,
                            license = licenses,
                        };
                        return View(details);
                    }
                    else
                    {
                        var details = new ProjectLicense
                        {
                            project = projects,
                            license = null,
                        };
                        return View(details);
                    }
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while retrieving project and license details.";
                return View(TempData);
            }
            return View();
        }
        [HttpGet]
        public IActionResult AddProjectUrl()
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            if (User.Identity.IsAuthenticated)
            {  
                return View();
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult AddProjectUrl(ProjectApiUrl model)
        {
            try
            {
                var record = new ProjectApiUrl(model);
                    _context.ProjectApiUrl.Add(record);
                    _context.SaveChanges();
                    return RedirectToAction("GetPorject");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while while saving record in database.";
                return View(TempData);
            }
        }
        [HttpGet]
        public IActionResult GetProjectsUrl()
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            if (User.Identity.IsAuthenticated)
            {
                var data = _context.ProjectApiUrl.ToList();
                return View(data);
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult EditProjectUrl(int id) 
        {
            Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            Response.Headers["Pragma"] = "no-cache";
            Response.Headers["Expires"] = "-1";
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var projecturl = _context.ProjectApiUrl.Where(p => p.id == id).FirstOrDefault();
                    if (projecturl != null)
                    {
                        return View(projecturl);
                    }
                    return NotFound();
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "An error occurred while retrieving project's url record.";
                return View(TempData);
            }
        }
        [HttpPost]
        public IActionResult EditProjectUrl(ProjectApiUrl model)
        {
            try
            {
                var project = _context.ProjectApiUrl.Where(p => p.id == model.id).FirstOrDefault();
                project.Project_Id = model.Project_Id;
                project.Api_Url = model.Api_Url;

Views/Project/AddProject.cshtml
@model Project_Management.Models.Projects.Project
@{
    ViewData["Title"] = "AddProject";
    Layout = "~/Views/Shared/_LayoutafterLogin.cshtml";
}
<script src="@Url.Content("~/js/particles.js")"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    #particles-js {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
        background-color: #121423;
    }


    html, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
    }

    /*body { background-image: url('path/to/your/image.jpg'); /* Replace 'path/to/your/image.jpg' with the actual image file path */ /*background-size: cover;*/ /* Adjust how the background image is displayed */ /* background-repeat: no-repeat;} */
    .rounded-button {
        height: 45px;
        width: 45px;
        border-radius: 50%; /* Set border radius to 50% to create a circular button */
        padding: 10px; /* Add padding for spacing within the circular button */
    }

    .custom-btn {
        background-color: antiquewhite; /* Replace with your desired background color */
        color: black; /* Replace with your desired text color */
        /* Add any other custom styling you need */
    }
</style>
<div id="particles-js">
</div>
<div class="container">
    <div class="row mt-lg-5">
        <div class="col-4 offset-4 border rounded p-lg-4" style="background-color: #e2642b; margin-top: 50px;">
            <div class="text-center">
                <h1 class="text-dark">Add New Project</h1>
            </div>
            <form method="post" asp-action="AddPorject">
                <div class="form-group">
                    <h6>Project Name</h6>
                    <input type="text" asp-for="Project_name" placeholder="Enter project name" class="form-control" autocomplete="off" />
                </div>
                <div><h5>  </h5></div>
                <div class="form-group">
                    <h6>Description</h6>
                    <input type="text" asp-for="Description" placeholder="Enter description" class="form-control" autocomplete="off" />
                </div>
                <div><h5>  </h5></div>
                <div class="form-group">
                    <h6>Start Date</h6>
                    <input type="date" asp-for="Start_Date" placeholder="Enter start date" class="form-control" autocomplete="off" />
                </div>
                <div><h2>  </h2></div>
                <div class="form-group">
                    <input type="submit" class="btn btn-dark float-lg-end" value="ADD" />
                </div>
            </form>
        </div>
    </div>
</div>
<script>

    //document.addEventListener("DOMContentLoaded", function () {
    // particlesJS initialization here...
    particlesJS('particles-js', {
        particles: {
            number: {
                value: 80
            },
            color: {
                value: '#ffffff'
            },
            size: {
                value: 3
            }
        },
        interactivity: {
            events: {
                onhover: {
                    enable: true,
                    mode: 'grab'
                }
            }
        }
    });

        //});

</script>

Views/Project/AddProjectUrl.cshtml
@model Project_Management.Models.Projects.ProjectApiUrl
@{
    ViewData["Title"] = "AddProjectUrl";
    Layout = "~/Views/Shared/_LayoutafterLogin.cshtml";
}
<script src="@Url.Content("~/js/particles.js")"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    #particles-js {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
        background-color: #121423;
    }


    html, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
    }

    /*body { background-image: url('path/to/your/image.jpg'); /* Replace 'path/to/your/image.jpg' with the actual image file path */ /*background-size: cover;*/ /* Adjust how the background image is displayed */ /* background-repeat: no-repeat;} */
    .rounded-button {
        height: 45px;
        width: 45px;
        border-radius: 50%; /* Set border radius to 50% to create a circular button */
        padding: 10px; /* Add padding for spacing within the circular button */
    }

    .custom-btn {
        background-color: antiquewhite; /* Replace with your desired background color */
        color: black; /* Replace with your desired text color */
        /* Add any other custom styling you need */
    }
</style>
<div id="particles-js">
</div>
<div class="container">
    <div class="row mt-lg-5">
        <div class="col-4 offset-4 border rounded p-lg-4" style="background-color: #e2642b; margin-top: 50px;">
            <div class="text-center">
                <h1 class="text-dark"></h1>
            </div>
            <form method="post" asp-action="AddProjectUrl">
                <div class="form-group">
                    <h6>Project Id</h6>
                    <input type="text" asp-for="Project_Id" placeholder="Enter project id" class="form-control" autocomplete="off" />
                </div>
                <div><h5>  </h5></div>
                <div class="form-group">
                    <h6>Project Url</h6>
                    <input type="text" asp-for="Api_Url" placeholder="Enter Project Url" class="form-control" autocomplete="off" />
                </div>
                <div><h5>  </h5></div>
                <div class="form-group">
                    <h6>Project Unique Id</h6>
                    <input type="text" asp-for="Project_Id_MIS" placeholder="Enter Project Unique Id" class="form-control" autocomplete="off" />
                </div>
                <div><h2>  </h2></div>
                <div class="form-group">
                    <input type="submit" class="btn btn-dark float-lg-end" value="ADD" />
                </div>
            </form>
        </div>
    </div>
</div>
<script>

    //document.addEventListener("DOMContentLoaded", function () {
    // particlesJS initialization here...
    particlesJS('particles-js', {
        particles: {
            number: {
                value: 80
            },
            color: {
                value: '#ffffff'
            },
            size: {
                value: 3
            }
        },
        interactivity: {
            events: {
                onhover: {
                    enable: true,
                    mode: 'grab'
                }
            }
        }
    });

                //});

</script>

Views/Project/EditProjectUrl.cshtml
@model Project_Management.Models.Projects.ProjectApiUrl
@{
    ViewData["Title"] = "AddProjectUrl";
    Layout = "~/Views/Shared/_LayoutafterLogin.cshtml";
}
<script src="@Url.Content("~/js/particles.js")"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    #particles-js {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
        background-color: #121423;
    }


    html, body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
    }
    /*body { background-image: url('path/to/your/image.jpg'); /* Replace 'path/to/your/image.jpg' with the actual image file path */ /*background-size: cover;*/ /* Adjust how the background image is displayed */ /* background-repeat: no-repeat;} */
    .rounded-button {
        height: 45px;
        width: 45px;
        border-radius: 50%; /* Set border radius to 50% to create a circular button */
        padding: 10px; /* Add padding for spacing within the circular button */
    }

    .custom-btn {
        background-color: antiquewhite; /* Replace with your desired background color */
        color: black; /* Replace with your desired text color */
        /* Add any other custom styling you need */
    }
</style>
<div id="particles-js">
</div>
<div class="container">
    <div class="row mt-lg-5">
        <div class="col-4 offset-4 border rounded p-lg-4" style="background-color: #e2642b; margin-top: 50px;">
            <div class="text-center">
            </div>
            <form method="post" asp-action="EditProjectUrl">
                <div class="form-group">
                    <h6>Project Id</h6>
                    <input type="text" asp-for="Project_Id" placeholder="Enter project id" class="form-control" autocomplete="off" />
                </div>
                <div><h5>  </h5></div>
                <div class="form-group">
                    <h6>Project Api Url</h6>
                    <input type="text" asp-for="Api_Url" placeholder="Enter Api Url" class="form-control" autocomplete="off" />
                </div>
                <div><h5>  </h5></div>
                <div class="form-group">
                    <h6>Project Unique Id</h6>
                    <input type="text" asp-for="Project_Id_MIS" placeholder="Enter Project's Unique Id'" class="form-control" autocomplete="off" />
                </div>
                <div><h2>  </h2></div>
                <div class="form-group">
                    <input type="submit" class="btn btn-dark float-lg-end" value="ADD" />
                </div>
            </form>
        </div>
    </div>
</div>
<script>

    //document.addEventListener("DOMContentLoaded", function () {
    // particlesJS initialization here...
    particlesJS('particles-js', {
        particles: {
            number: {
                value: 80
            },
            color: {
                value: '#ffffff'
            },
            size: {
                value: 3
            }
        },
        interactivity: {
            events: {
                onhover: {
                    enable: true,
                    mode: 'grab'
                }
            }
        }
    });

            //});

</script>

Views/Project/GetPorject.cshtml
@model IEnumerable<Project_Management.Models.Projects.Project>
@{
    ViewData["Title"] = "GetProject";
    Layout = "~/Views/Shared/_LayoutafterLogin.cshtml";
}

<style>
    body {
        background-color: #121423;
    }
    .white-background {
        color: white;
    }
    .table thead th:nth-child(1),
    .table tbody td:nth-child(1)
    {
        width:10%;
    }
    .table thead th:nth-child(2),
    .table tbody td:nth-child(2)
    {
        width:20%;
    }
    .table thead th:nth-child(3),
    .table tbody td:nth-child(3)
    {
        width:30%; /* Adjust the value as needed */
    }

    .table thead th:nth-child(4),
    .table tbody td:nth-child(4)
    {
        width: 15%;
    }

    .table thead th:nth-child(5)
    .table tbody td:nth-child(5) {
        width: 25%; /* Adjust the value as needed */
    }
    .btn-color{
        background-color: antiquewhite
    }

</style>

<p>
    <a asp-action="AddPorject" class="btn btn-success">Add Porject</a>
    <a asp-action="GetProjectsUrl" class="btn btn-success">Project API Links</a>
    <a asp-controller="License" asp-action="GetLicense" class="btn btn-success">View Licenses</a>
</p>
<table class="table" id="dataTableData">
    <thead>
        <tr style="background-color: #e2642b">
            
            <th>
                @Html.DisplayNameFor(model => model.Project_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Start_Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="white-background">
                    @Html.DisplayFor(modelItem => item.Project_Id)
                </td>
                <td class="white-background">
                    @Html.DisplayFor(modelItem => item.Project_name)
                </td>
                <td class="white-background">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td class="white-background">
                    @Html.DisplayFor(modelItem => item.Start_Date)
                </td>
                <td>
                    <a asp-action="UpdatePorject" asp-route-id="@item.Id" class="btn btn-outline-light" title="Edit Project">
                    <i class="fas fa-pencil-alt"></i>
                    </a>
                    <form asp-action="DeletePorject" method="post" asp-route-id="@item.Id" class="d-inline">
                        <button type="submit" class="btn btn-outline-danger" title="Delete" onclick="return confirm('Are you sure you want to delete @item.Project_name ?')">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                    <a asp-action="ProjectDetails" asp-route-id="@item.Id" class="btn btn-outline-primary" title="View Details">
                        <i class="fas fa-info-circle"></i></a>
                    <a asp-controller="License" asp-action="AddLicense" asp-route-id="@item.Id" class="btn btn-secondary">Add License</a>
                   
                </td>
            </tr>
        }
    </tbody>
</table>
@section scripts{
    <script src="~/js/datatable_file.js"></script>
}